### ISSUE TITLE
Unsupported architecture: Qwen2ForCausalLM

### ISSUE THREAD

**Issue by Bugjudger** [BytedanceDouyinContent/SAIL-VL2#3]
In this line:
processor = AutoProcessor.from_pretrained(PATH, trust_remote_code=True)

error:
Unsupported architecture: Qwen2ForCausalLM

**Comment by ajayasai** [comment]
Facing same issue.

As per ChatGPT:

When transformers builds a Config object it sometimes needs to create a default instance of the config class (to show defaults, call to_json_string() for logging, or compute a “diff” of defaults). To do that it calls the config class constructor with no arguments (i.e. SAILVLConfig()), and that triggers the code in configuration_sailvl.py:

configuration_sailvl.py's __init__ inspects the llm_config argument. If llm_config is None it assigns a default of {'architectures': ['Qwen2ForCausalLM']} and then checks whether that architecture is supported. Its unsupported raising ValueError('Unsupported architecture: Qwen2ForCausalLM')

**Comment by intuitifai** [comment]
Clicked on the problematic line and it navigated to a file: `configuration_sailvl.py`

Under the class SAILVLConfig, at line 46, we see the code:

```python
        if vision_config is None:
            vision_config = {}
            logger.info('vision_config is None. Initializing the SAILViTConfig with default values.')

        if llm_config is None:
            llm_config = {'architectures': ['Qwen2ForCausalLM']}
            logger.info('llm_config is None. Initializing the LlamaConfig config with default values (`LlamaConfig`).')

        self.vision_config = SAILViTConfig(**vision_config)
        if llm_config['architectures'][0] == 'LlamaForCausalLM':
            self.llm_config = LlamaConfig(**llm_config)
        elif llm_config['architectures'][0] == 'Qwen3ForCausalLM':
            self.llm_config = Qwen3Config(**llm_config)
        else:
            raise ValueError('Unsupported architecture: {}'.format(llm_config['architectures'][0]))
```

From what I understood, somehow `llm_config['architectures'][0]` is set to `Qwen2ForCausalLM`, but valid configurations are only either `LlamaForCausalLM` or `Qwen3ForCausalLM`. 

I tried to do a quick (and stupid) fix by just changing it to Qwen3ForCausalLM if llm_config is None, but that results in another error:
```
ImportError: cannot import name 'LossKwargs' from 'transformers.utils' 
```

**Comment by Ladazhx** [comment]
我试了一下，需要使用transformers==4.51.0，建议官方文档中能说明一下。

**Comment by ajayasai** [comment]
yes it works with transformers==4.51.0

**Comment by KevinClaint** [comment]
I meet this question “ NameError: name 'init_empty_weights' is not defined” in transformers==4.51.0，and I solve it when i ungrade transformers==4.51.1
